{{- if .Values.secrets }}
{{- range $key,$value := .Values.secrets }}
---
apiVersion: v1
data:
  {{ $value.secret_key }}: {{ $value.secret_pass | b64enc }}
kind: Secret
metadata:
  name: {{ $value.secret_name }}
  namespace: {{ $.Values.fruit }}
type: Opaque
{{- end }}
{{- end }}
