variable fruit { }
variable aws_region { }
variable aws_profile { }
variable aws_cluster_arn { }
variable aws_vpc_id { }
variable aws_domain { }
variable iam_role_name { }
variable rds_engine { }
variable rds_engine_version { }
variable rds_instance_class { }
variable rds_allocated_storage { }
variable rds_multi_az { }
variable rds_identifier { }
variable rds_db_name { }
variable rds_username { }
variable rds_password { }
variable rds_auto_minor_version_upgrade { }
variable rds_maintenance_window { }
variable rds_backup_window { }
variable rds_backup_retention_period { }
variable rds_vpc_security_group_ids { }